#!/bin/sh
[ $# -eq 0 ] && echo "usage: ${0//*\//} {dir_of_a} [rev]]" && exit 2
dir_a="$1"
[ "$2" = "rev" ] && is_reverse=1
find \
  -name \*.csv -prune -o -name \*.js -prune -o -name dist -prune -o -name node_modules -prune -o -name semantic -prune -o \
  -name uploads -prune -o -name fonts -prune -o -name logs -prune -o -name .git -prune -o -name .eee\? -prune -o -name tags -prune -o -name user_guide -prune -o -name errors.err -prune -o -name sessions -prune -o -name filing -prune -o -type f -print \
|awk -v dir_a="$dir_a" -v is_reverse=${is_reverse:-0} 'BEGIN{
		print "i=1";
	}
	{
		gsub(/ /,"?");
    a=sprintf("%1c%s/%s%1c",0x27,dir_a,$0,0x27);
    b=sprintf("%1c%s%1c",0x27,$0,0x27);
		printf("diff -q %s %s\n",a,b);
		printf("x=$?; [ \"$x\" -eq 1 ] && echo \"$i: ----------\" && echo \"$ vimdiff %s %s\"",a,b);
		if(is_reverse==0){
			printf(" && echo \"$ cp %s %s\"",b,a);
		}else{
			printf(" && echo \"$ cp %s %s\"",a,b);
		}
		printf(" && i=$((i + 1)) && echo\n");

		printf("[ \"$x\" -eq 2 ] && echo \"$i: ----------\"");
		if(is_reverse==0){
			printf(" && echo \"$ cp %s %s\"",b,a);
		}else{
			printf(" && echo \"$ cp %s %s\"",a,b);
		}
		printf(" && i=$((i + 1)) && echo\n");
	}'
