#!/bin/bash
#
# usage: gitundo [file ...]
#
if [ "$#" -eq 0 ]; then
  git status 

  printf "contiue? (y/n): "
  read yn
  [ "$yn" != "y" ] && exit 2

  files=`git status | awk '$2=="modified:"{printf($NF " ");}'`
else
  files=$*
fi


if [ -z "$files" ]; then
  echo "no modified files."
  exit 1
fi

co_files=""
for f in $files
do
  if [ -f $f ]; then
    rm -i $f
  fi
  if [ -f $f ]; then
    echo "$f: skipped."
    continue
  fi
  co_files="$co_files $f"
done

if [ -z "$co_files" ]; then
  echo "no target files."
  exit 1
fi
set -x
git checkout HEAD $co_files && git pull
exit $?

