#!/bin/bash
#
# usage: gitup COMMIT_MESSAGE
#
git status 

printf "contiue? (y/n): "
read yn
[ "$yn" != "y" ] && exit 2

if [ $# -eq 0 ];then
  #printf "Enter commit message.: "
  #read m
  echo 'commit message is not specified.'
  exit 2
else
  m="$*"
fi

files=`git status | awk 'match($1,"modified:")>0 || match($1,"new")>0 {printf($NF " ");}'`

if [ -z "$files" ]; then
  echo "no modified files."
  exit 1
fi

git add $files && git commit -m "$m" && git push
exit $?

