#!/bin/bash
# purpose: get the native Windows path from the WSL path. it's similar to cygpath (cygwin, msys)
myname=${0//*\//}
[ "$1" = "--single_escape" ] && is_single_escape=1 && shift
[ $# -ne 1 ] && echo "usage: $myname [--single_escape] PATH" 1>&2 && exit 2
echo "$1" | grep -q '^file://'
if [ $? -eq 0 ]; then
  p=$(echo "$1" | sed -e 's#^file://##')
  if [ ${is_single_escape:-0} -eq 0 ]; then
    p=$(printf '%b\n' "${p//%/\\x}")
  else
    p=$(printf '%b\n' "${p//%/\x}")
  fi
  #p=$(echo "$1" | sed -e 's#^file://##' -e 's/%/\\x/g')
  #p=$(printf '%b\n' "$p")
else
  p="$1"
fi
echo $p | grep -q '^/'
if [ $? -ne 0 ]; then
  abs_path="$(cd $(dirname $p) && pwd)/$(basename $p)" 1>&2
else
  abs_path="$p"
fi
abs_path="$(echo $abs_path|sed -e 's/^\/\//\//')"
wsl_file_prefix='\\\\wsl$\\Ubuntu-20.04'
win_file_re='^/mnt/'
has_cygpath=$(type cygpath 1>/dev/null 2>&1;echo $?)
[ "$has_cygpath" -eq 0 ] && cygpath -w $abs_path && exit 0
echo|awk -v abs_path="$abs_path" -v wsl_file_prefix="$wsl_file_prefix" -v win_file_re="$win_file_re" 'match(abs_path,win_file_re)>0{sub(win_file_re,"",abs_path);abs_path=gensub(/^([a-z])/,"\\1:","g",abs_path);}match(abs_path,/^\//)>0{abs_path=sprintf("%s/%s",wsl_file_prefix,gensub(/^\//,"","g",abs_path));}END{gsub(/\//,"\\",abs_path);print abs_path;}'
exit $?
