#!/bin/bash
# purpose: get the native Windows path from the WSL path. it's similar to cygpath (cygwin, msys)
myname=${0//*\//}
[ $# -ne 1 ] && echo "usage: $myname PATH" 1>&2 && exit 2
abs_path="$(cd $(dirname $1) && pwd)/$(basename $1)"
abs_path="$(echo $abs_path|sed -e 's/^\/\//\//')"
wsl_file_prefix='\\\\wsl$\\Ubuntu-20.04'
win_file_re='^/mnt/'
has_cygpath=$(type cygpath 1>/dev/null 2>&1;echo $?)
[ "$has_cygpath" -eq 0 ] && cygpath -w $abs_path && exit 0
echo|awk -v abs_path="$abs_path" -v wsl_file_prefix="$wsl_file_prefix" -v win_file_re="$win_file_re" 'match(abs_path,win_file_re)>0{sub(win_file_re,"",abs_path);abs_path=gensub(/^([a-z])/,"\\1:","g",abs_path);}match(abs_path,/^\//)>0{abs_path=sprintf("%s/%s",wsl_file_prefix,gensub(/^\//,"","g",abs_path));}END{gsub(/\//,"\\",abs_path);print abs_path;}'
exit $?
